/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:18e9dac3-b258-4441-9644-5c1458241351",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_hy4UaqomQ",
  aws_user_pools_web_client_id: "1muq26k09b0841qradev29nmd4",
  oauth: {},
};

export default awsmobile;
